### ISSUE TITLE
Ruumiloome ekspertryhmale teemapuu ja see lisada yldisele teemapuule

### ISSUE THREAD

**Issue by mcanet** [Demokraatialabor/Protsessid#13]
Lisame alajaotused, sest hea on j22da riigieelarve strateegia jaotuse juurde.

**Comment by laurakalda** [comment]
Potentsiaalsed lisateemad (KODARas kajastatud teemade näitel): sooline jaotus, noored

**Comment by infokujur** [comment]
Siia panin ühe puuna riigieelarve puu: https://docs.google.com/spreadsheets/d/1z_mg2WrgHGE541uOnp-hXcZGLPfgbGWR4lLj2REszhw/edit#gid=994305516

Seda märgime, siis metapdf
