### ISSUE TITLE
Lisada horisontaalsed teemad

### ISSUE THREAD

**Issue by mcanet** [Demokraatialabor/Protsessid#14]

**Comment by mcanet** [comment]
Ruumiloome, teadus ja arendus, eesti keel ja kirjandus, riigivalitsemine jne

**Comment by mcanet** [comment]
@infokujur Palun pane enda peale ja loo uus tabel.

**Comment by infokujur** [comment]
Tabel loodud https://docs.google.com/spreadsheets/d/1z_mg2WrgHGE541uOnp-hXcZGLPfgbGWR4lLj2REszhw/edit#gid=994305516
